### ISSUE TITLE
I need help with the patchouli related api.

### ISSUE THREAD

**Issue by Engel-Blut** [navarayuk/ShadowsAPIs#1]
https://pastebin.com/KMZxx9kn
https://imgur.com/kRneMng

Firstly, sorry for my bad English, I'm using Google Translate and it may not translate what I want to say in the best way.

I'm trying to use your plugin to be able to develop my mod using patchouli, but every time the api is active in the "external apis" it keeps giving this error in the console and talking about gradle on the screen as shown in the photo of my mcreator screen.

If I remove the patchouli api, and let mcreator redo the workspace, the mod works normally. So I think it must be a problem with the API, I'm new to this area so I don't have the knowledge to say that.

![problemacompatchouli](https://github.com/navarayuk/ShadowsAPIs/assets/34969506/cda89a6c-ab28-4801-b2cf-b4c7f7cf9396)
[KMZxx9kn.txt](https://github.com/navarayuk/ShadowsAPIs/files/12827083/KMZxx9kn.txt)

**Comment by navarayuk** [comment]
Please try https://github.com/navarayuk/ShadowsAPIs/releases/tag/1.0.3.9 or [MCreator - ShadowsAPI 1.0.3.9](https://mcreator.net/system/files/2023-10/ShadowsAPI_1039.zip) this was already fixed here https://github.com/navarayuk/ShadowsAPIs/commit/ae96b17620bdc27d6490101d1261baaa868bc97d

Also this fix will not work until 2023.4 as this mod needs Forge 47.1.1 and 2023.3 only has Forge 47.1.0
